const DEVICE_LABELS: Record<string, string> = {
  heladera: 'Heladera',
  freezer: 'Freezer',
  lavarropas: 'Lavarropas',
  secarropa: 'Secarropa',
  cocina: 'Cocina',
  horno: 'Horno',
  microondas: 'Microondas',
  campana: 'Campana',
  lavavajillas: 'Lavavajillas',
  calefactor: 'Calefactor',
  'aire-split': 'Aire Split',
  'aire-central': 'Aire Central',
  termotanque: 'Termotanque',
  balanza: 'Balanza',
  router: 'Router',
  switch: 'Switch',
  cableado: 'Cableado',
  camaras: 'Cámaras',
  ups: 'UPS',
  plc: 'PLC',
  variador: 'Variador',
  'tablero-ind': 'Tablero Industrial',
  motor: 'Motor',
  'camara-frio': 'Cámara Frío',
  chiller: 'Chiller',
  compresor: 'Compresor',
  frigobar: 'Frigobar',
  pivote: 'Pivote',
  'bomba-sumergible': 'Bomba Sumergible',
  'panel-solar': 'Panel Solar',
  inversor: 'Inversor',
  'grupo-electrogeno': 'Grupo Electrógeno',
  tractor: 'Tractor',
  cosechadora: 'Cosechadora',
  ordeñadora: 'Ordeñadora',
  bebedero: 'Bebedero',
  boyero: 'Boyero',
  tablero: 'Tablero',
  instalacion: 'Instalación',
};

export function deviceLabel(path: string): string {
  const slug = path.split('/').pop() || path;
  return DEVICE_LABELS[slug] || slug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
